// Generated by delombok at Sat May 07 16:07:13 EDT 2022

import java.util.ArrayList;
import java.util.Collection;

class ArrList {
    ArrayList<String> list;
    int x;

    ArrList(ArrayList<String> list, int x) {
        this.list = list;
        this.x = x;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "new ArrList(" + BetterToString.make(this.list) + ", " + BetterToString.make(this.x) + ")";
    }
}

class BetterToString {
    public static <T> String make(T obj) {
        if (obj instanceof String) {
//      // TODO: actually do the conversion
//      return "\"" + obj.toString() + "\"";
            String buffer = "";
            char[] chars = ((String) obj).toCharArray();
            for (char c : chars) {
                switch (c) {
                    case '\t':
                        buffer += "\\" + "t";
                        break;
                    case '\b':
                        buffer += "\\" + "b";
                        break;
                    case '\n':
                        buffer += "\\" + "n";
                        break;
                    case '\r':
                        buffer += "\\" + "r";
                        break;
                    case '\f':
                        buffer += "\\" + "f";
                        break;
                    case '\'':
                    case '\"':
                    case '\\':
                        buffer += "\\" + c;
                        break;
                    default:
                        buffer += c;
                        break;
                }
            }
            return "\"" + buffer + "\"";
        } else if (obj instanceof ArrayList) {
            String buffer = "";
            buffer += "new ArrayList<>(Arrays.asList";
        } else {
            return obj.toString();
        }
    }
}
